name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      TEST_STATUS: ""
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      id: test
      run: |
        npm test | tee test-output.txt
        if grep -q "failed" test-output.txt; then
          echo "Tests failed"
          echo "failed" > test-status.txt
        else
          echo "Tests passed"
          echo "PASSED" > test-status.txt
        fi
      shell: bash
    - name: Set test status
      id: set_test_status
      run: echo "TEST_STATUS=$(cat test-status.txt)" >> $GITHUB_ENV
    - name: Check test status
      run: |
        if [ "$TEST_STATUS" == "failed" ]; then
          exit 1
        fi
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: test-results/
        retention-days: 30
